### ISSUE TITLE
Release 1.7

### ISSUE THREAD

**Issue by andrewimm** [ParsePlatform/Parse-SDK-JS#136]
Planned changelog:
- [x] Store server data and pending ops on-object when single instance mode is disabled. This will prevent memory leaks. (structural change only, does not affect APIs or behavior)
- [x] Default to setting A+ Compliance to `true`. See #57 for more details. (landed in 96e211d4fad49929d3db522254d3540c14ee3a77)
- [x] Enable native-style construction of `Parse.Promise`. See #57 for more details. (landed in 5e5c444d0bd02d5955c8b43b6257ca11b74eeb14)
- [x] Re-commit #115, changing the behavior of `Parse.Promise.when()`. The response provided to the asynchronous callback will match the style of its arguments. (landed in 7da2856b18ca1672766612700139757300ecbf62)
- [x] Add `revert()` instance method to ParseObject (landed in 7c16dee0f90a6d85bb409851de86107a04007c06)

When these changes have all been committed to master, and end-to-end tested, we'll release 1.7.0

**Comment by TylerBrock** [comment]
This would be great. Thanks Andrew

**Comment by grantland** [comment]
I :heart: #115

**Comment by mohnazemi** [comment]
Changelogs were not updated for the last several releases on the Downloads page. Is there a reason ?

**Comment by andrewimm** [comment]
@mohnazemi the source of truth for changelogs will always be here on this repo: https://github.com/ParsePlatform/Parse-SDK-JS/releases

I'll update the downloads page to include the last few releases

**Comment by srameshr** [comment]
@andrewimm Caching built into the JS SDK would be a very useful addition. App's built for the webview in IOS and Android platform would have a huge boost. In the docs you clearly say don't use REST API when you have native sdk for your platform.

**Comment by andrewimm** [comment]
@srameshr we are working out a number of strategies for caching, but it will not be an official feature until at least 1.8. It will most likely end up being a plug-in that can be added to the SDK, rather than a change to the SDK itself.

**Comment by srameshr** [comment]
Any particular date on which, this would be available?

**Comment by andrewimm** [comment]
@srameshr As a rule, we don't commit to dates for releases. Even less so for features where we're still unsure what to implement.

As it is, it's trivial to implement your own cache in your own application:
```js
updateCache(object) {
  let entry = object.className + ':' object.id;
}
```

**Comment by andrewimm** [comment]
@srameshr As a rule, we don't commit to dates for releases. Even less so for features where we're still unsure what to implement.

As it is, it's trivial to implement your own cache in your own application. This is a simple implementation of one:
```js
updateCache(object) {
  let identifier = object.className + ':' object.id;
  let currentCache = JSON.parse(localStorage.get('cachedObjects') || '{}');
  currentCache[identifier] = true;
  // Store object to localStorage
  localStorage.set(identifier, JSON.stringify(object._toFullJSON()));
  // Store updated object index to localStorage
  localStorage.set('cachedObjects', JSON.stringify(currentCache));
}

getCachedObjects() {
  let objects = {};
  let currentCache = JSON.parse(localStorage.get('cachedObjects') || '{}');
  for (let identifier in currentCache) {
    let objectString = localStorage.get(identifier);
    if (objectString) {
      try {
        objects[identifier] = Parse.Object.fromJSON(JSON.parse(objectString));
      catch (e) { }
    }
  }
  return objects;
}
```

**Comment by srameshr** [comment]
I am doing something similar to this ...

**Comment by jmornar** [comment]
@andrewimm Although I know you are not commiting to dates, I have to ask do you have at least a rough estimation of when version 1.7 with memory leak (when running in server environment) fix could be released? just to know if it worth to wait or we have to look for a new solution as we already have this issue on production for some time now?

**Comment by andrewimm** [comment]
I'm aiming to get something out this week -- the changes involved are pretty significant, but I'm about 2/3 of the way through. In the meantime, I've posted a number of potential workaround ideas in other threads related to the issue.

**Comment by andrewimm** [comment]
When #164 lands (hopefully later today), I'll be cutting a release as `1.7.0-rc1`. As npm goes, you'll be able to explicitly install this version for testing, but it won't show up in the normal version lists, and won't be included in any semver ranges.

Once we're comfortable that there are no regressions or unintended changes, we'll cut an official 1.7.0 release for npm, our web CDN, and cloud code.

**Comment by andrewimm** [comment]
The current master branch passes all unit and integration tests, so I've released `1.7.0-rc1`. Download away!

**Comment by andrewimm** [comment]
Since there has been no negative feedback about the RC, I'll be releasing 1.7.0 to npm tomorrow morning, including the changes from #179

**Comment by TylerBrock** [comment]
Yeah we've been running it in production since about 24 hours after the release. Seems to work well.
